<header class="header-section sticky-top"> 
    <?php
        
        require_once('data/database.php');
		include('template/navbar.php');
        if(connectDB()){
            
            closeDB();
        }            
    ?>

</header>
<section class="container index-main">
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
	asdsadad<br>
</section>
